name: Alpine-APK-Collection (Branch)
run-name: ${{ github.actor }} is Collecting New RPMs for ${{ github.ref_name }} 🚀
on:
  push:
    branches-ignore:
      - main
  release:
    types: [edited, released]
  workflow_dispatch:

jobs:
  Date:
    runs-on: ubuntu-24.04
    outputs:
      Date: ${{ steps.date.outputs.date }}
    steps:
      - name: Get current date
        id: DATE
        run: |
          echo "Setting Date"
          echo "DATE=$(date '+%Y%m%d-%H%M')" >> $GITHUB_OUTPUT
          echo -e "\nWrote to file:\n$GITHUB_OUTPUT\n"
          echo "Values:"
          cat $GITHUB_OUTPUT

      - name: Get disk space
        id: DISK
        run: |
          echo -e "\nUser ID:\n$(id)"
          df -h
          echo -e "\nDisk List"
          sudo fdisk -l | grep -i disk
          echo -e "\nPermissions on /mnt"
          ls -alht /mnt

  Collect-APKs:
    needs: [Date]
    runs-on: ubuntu-24.04
    env:
      GH_TOKEN: ${{ github.token }}
      WORKDIR: /mnt/${{vars.COLLECTOR }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          echo "PATH=$PATH:$PWD/scripts" >> $GITHUB_ENV
          sudo apt-get update -y
          sudo apt-get install -y mkisofs isomd5sum wget

      - name: Run Collection for ${{ vars.COLLECTOR }}
        run: |
          sudo mkdir -p ${{ env.WORKDIR }}/${{ vars.COLLECTOR }}
          sudo chown -R $USER ${{ env.WORKDIR }}
          echo "Collecting ${{ vars.COLLECTOR }} APKs"
          # Rsync only the latest version and selected repos/arch
          rsync -av \
            --update \
            --hard-links \
            --delete \
            --delete-after \
            --delay-updates \
            --timeout=600 \
            --include "v3.21/" \
            --include "v3.21/main/" \
            --include "v3.21/main/x86_64/***" \
            --exclude "*" \
            rsync://rsync.alpinelinux.org/alpine ${{ env.WORKDIR }}/${{ vars.COLLECTOR }}

      - name: Show Files
        run: ls -Alht ${{ env.WORKDIR }}

      - name: List disks
        run: df -h ${{ env.WORKDIR }}

      # - name: Upload reposync log
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.log
      #     path: ${{ env.WORKDIR }}/${{ vars.COLLECTOR }}.log
      #     if-no-files-found: error

      - name: Show Consumption
        run: |
          echo -e "Disk Usage:\n$(du -chs ${{ env.WORKDIR }})\n"
          echo -e "Disk Space:\n$(df -h ${{ env.WORKDIR }})\n"
          echo -e "File Listing:\n$(ls -alhS ${{ env.WORKDIR }}*)\n"

      - name: Copy README to ${{ vars.COLLECTOR }} ISO
        run: cp -v README.md ${{ env.WORKDIR }}

      - name: ISO Table of contents
        run: |
          cd ${{ env.WORKDIR }}
          tree ${{ vars.COLLECTOR }} \
          | tee ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso.txt
          cp -v ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso.txt ${{ vars.COLLECTOR }}

      - name: Upload ISO ToC artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso.txt
          path: ${{ env.WORKDIR }}/${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso.txt
          if-no-files-found: error

      - name: Make ${{ vars.COLLECTOR }} ISO
        run: |
          echo "Making ISO of ${{ vars.COLLECTOR }}"
          cd ${{ env.WORKDIR }}
          mkisofs -J -R -v -T -l \
            -V ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }} \
            -A ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }} \
            -o ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso \
            ${{ vars.COLLECTOR }}

      - name: Implant MD5 sum into ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso
        run: implantisomd5 ${{ env.WORKDIR }}/${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso

      - name: Generate ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso Hash
        run: |
          cd ${{ env.WORKDIR }}
          sha256sum -b ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso \
          | tee ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso.sha

      - name: Show ISO Files
        run: ls -sS1h ${{ env.WORKDIR }}/*.iso*

      - name: Upload ISO files
        uses: actions/upload-artifact@v4
        with:
          name: ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso
          path: ${{ env.WORKDIR }}/${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso*
          if-no-files-found: error

      # Cleanup
      - name: Clean up
        run: |
          cd ${{ env.WORKDIR }}
          echo "Remove ${{ vars.COLLECTOR }}"
          rm -rf ${{ vars.COLLECTOR }}
          echo "Remove Artifacts"
          rm -rfv ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso
          rm -rfv ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso.sha
          rm -rfv ${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso.txt
          echo "Done"

  Release:
    runs-on: ubuntu-24.04
    needs: [Date, Collect-APKs, Sharepoint]
    permissions:
      contents: write
      pull-requests: read
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          pattern: "*.iso.*"

      - name: Show Artifacts
        run: ls -sS1h *.iso.*

      # Section to actually create a release

  # Upload to Sharepoint Job
  Sharepoint:
    runs-on: ubuntu-24.04
    needs: [Date, Collect-APKs]
    permissions:
      contents: write
      pull-requests: read
    env:
      GH_TOKEN: ${{ github.token }}
    steps:

      - name: Setup upload directory
        run: |
          echo "Create mnt directory and bindmount"
          echo -e "\nUser ID:\n$(id)"
          mkdir -p mnt
          sudo mount --bind -o umask=022,gid=118,uid=1001 /mnt mnt
          sudo chown -R runner:docker /mnt
          # echo -e "\nFile Listing\n$(ls -alht mnt)"

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          pattern: "${{ vars.COLLECTOR }}-${{ needs.Date.outputs.Date }}.iso*"
          path: mnt

      - name: List Artifacts
        run: |
          echo -e "\nDisk mounts:\n$(df -h|grep mnt)"
          echo -e "\nFile Listing:\n$(ls -1sSh mnt/*.iso*)"

      # Send Artifacts to Sharepoint
